name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
            - имя: Загрузить артефакт сборки
  используется: actions/upload-artifact@v7.0.1
  с:
    # Название артефакта. Если значение параметра `archive` равно `false`, то имя загружаемого файла будет совпадать с именем артефакта.
    имя: # необязательно, по умолчанию — артефакт
    # Файл, каталог или шаблон с подстановочным знаком, описывающий, что нужно загрузить.
    путь:
    # Желаемое поведение, если файлы не найдены по указанному пути.
Доступные варианты:
  Предупреждение: Вывести предупреждение, но не прерывать выполнение действия.
  Ошибка: Действие завершилось с ошибкой.
  игнорировать: не выводить никаких предупреждений или ошибок, действие не завершается с ошибкой.

    if-no-files-found: # необязательный параметр, по умолчанию выдается предупреждение
    # Продолжительность, по истечении которой артефакт будет удален из памяти (в днях). 0 означает использование срока хранения по умолчанию.
Минимальный срок — 1 день. Максимальный — 90 дней, если иное не указано на странице настроек репозитория.

    retention-days: # необязательно
    # Уровень сжатия, применяемый Zlib к архиву артефакта. Значение может варьироваться от 0 до 9: - 0: Без сжатия - 1: Максимальная скорость - 6: Сжатие по умолчанию (аналогично GNU Gzip) - 9: Максимальное сжатие. Более высокие уровни обеспечивают лучшее сжатие, но увеличивают время выполнения. Для больших файлов, которые трудно сжать, рекомендуется значение 0 для значительно более быстрой загрузки.

    compression-level: # необязательный параметр, по умолчанию 6
    # Если true, артефакт с совпадающим именем будет удален перед загрузкой нового. Если false, действие завершится неудачей, если артефакт с заданным именем уже существует. Не завершится неудачей, если артефакт не существует.

    overwrite: # необязательный параметр, по умолчанию false
    # Если true, скрытые файлы будут включены в артефакт. Если false, скрытые файлы будут исключены из артефакта.

    include-hidden-files: # необязательный параметр, по умолчанию false
    # Если true, артефакт будет заархивирован (заархивирован) перед загрузкой. Если false, артефакт будет загружен как есть, без архивирования. Если `archive` равно `false`, можно загрузить только один файл. Имя файла будет использоваться в качестве имени артефакта (без учета параметра `name`).

    архив: # необязательный параметр, по умолчанию true
          
